### ISSUE TITLE
Atmega 2560

### ISSUE THREAD

**Issue by grogcw** [Dlloydev/jtag2updi#12]
Hi !

I'd like to use your schematics and code to make a HV/PCHV with an Arduino Mega 2560.

I think that the only changes to make are in sys.h for pin definitions.

Do I have to tinker only there or is there somewhere else to define things for this to work ?

Thanks for taking care,

Cheers !

**Comment by Dlloydev** [comment]
OK, I've uploaded a commit that should give you a head start (untested).
Let me know if there's any issues or if you'd like to make any changes.

Here's the pinout diagram:

![ATmega2560](https://user-images.githubusercontent.com/63488701/106788358-d72c7880-661e-11eb-93f1-2b37dddfab8f.gif)

**Comment by grogcw** [comment]
Hi !

Thanks for your quick reply !

I don't have the electronics to make any charge pump at the moment, but I think I could rig something with a 12v power supply with a tension divider.

Anyway, I'll keep you in touch !

Cheers !
