### ISSUE TITLE
In this diagram, it is not clear where to connect tinyAVR?

### ISSUE THREAD

**Issue by P55-rgb** [Dlloydev/jtag2updi#15]
In this diagram, it is not clear where to connect tinyAVR?
Can you add it (tinyAVR) to the diagram?
https://raw.githubusercontent.com/wiki/Dlloydev/jtag2updi/images/NanoProgSch.png
https://oshpark.com/shared_projects/cxgBKsCQ

**Comment by Dlloydev** [comment]
From the diagram, its just the 3 connections here, where T5V is the target 5V power (this comes from A0-A5).
![image](https://user-images.githubusercontent.com/63488701/116489131-25d66100-a862-11eb-9871-759b60d3b435.png)
For steady 5V power, this can be taken from the 6-pin connector on the Nano (see Arduino's documentation to identify GND and 5V on this connector.

**Comment by P55-rgb** [comment]
![image](https://user-images.githubusercontent.com/63473590/116496998-8dc39080-a8d0-11eb-8135-dfac14c7a946.png)
Two questions.
1. HVUPDI = 12v?
2. Pin 6=UPDI on tiny412, where to connect?

**Comment by Dlloydev** [comment]
Yes, the HVUPDI signal will have a fast 12V pulse (about 400µs) just after power-up, but it will normally be 5V. Pin PA0 (UPDI) is 12V tolerant.

![image](https://user-images.githubusercontent.com/63488701/116498050-d2bad900-a876-11eb-99b9-65d8ae5397ce.png)

**Comment by P55-rgb** [comment]
According to the documentation on tiny412 page 385, a 12V pulse should appear on the UPDI pin.
I don't understand how your HVUPDI circuit generates a 12 volt pulse?
Explain the scheme...

**Comment by Dlloydev** [comment]
Its a Dickson Charge Pump ... explained in the [documentation](https://github.com/Dlloydev/jtag2updi/wiki/Arduino-Nano-HV-UPDI-Programmer) (scroll down near the bottom).

**Comment by P55-rgb** [comment]
![image](https://user-images.githubusercontent.com/63473590/116501394-dbdd9180-a8da-11eb-8ce1-be2eb90f76b1.png)
LEDs: Red, yellow, blue.
There is only one LED1 in the diagram.
Is LED1, this is: red, yellow, or blue? )))
Where are the LEDs installed (red, yellow, blue) and what is their designation?

**Comment by Dlloydev** [comment]
The red and yellow led are on the Nano. LED1 is the blue LED which indicates the 12V pulse, this is on the programmer PCB. There's [images](https://raw.githubusercontent.com/wiki/Dlloydev/jtag2updi/images/NanoProgTop.png) available at the bottom of the documentation link, gerber files are available at Osh Park.

**Comment by P55-rgb** [comment]
https://oshpark.com/shared_projects/cxgBKsCQ
How much will it cost to deliver your programmer to Russia, to Tomsk?

**Comment by Dlloydev** [comment]
Sorry, I'm not building and selling these as I don't have the necessary equipment (never did receive the reflow oven purchased just prior to the pandemic). I'll need to update the info at the Tindie store.
