### ISSUE TITLE
2. series

### ISSUE THREAD

**Issue by DanSkareda** [Dlloydev/jtag2updi#16]
Hi. I can't compile this code for attiny 2. series (attiny 1624). Will you be support for MCU 2. Series? Have a nice day, Dan.

**Comment by Dlloydev** [comment]
Hello Dan,
The tinyAVR 2 Family looks quite interesting, but unfortunately I won't have time in the near future to develop support for it as a UPDI programmer (or HV UPDI programmer), but there are various other options presently available.
