### ISSUE TITLE
Question for AVR-DA

### ISSUE THREAD

**Issue by sstaub** [Dlloydev/jtag2updi#9]
Can the programmer also used with DxCore (AVR-DA and AVR-DB) and MegaCoreX (AtMega4809...)?

**Comment by Dlloydev** [comment]
Good question. I've used the Nano Every with MegaCoreX  and got to the point of everything working except the serial. I needed to do more investigation with the built-in SAMD programmer chip and UPDI line. 

Should be no issues adding full HV programming support to the 4809 on its own ... I'll do this first prior to adding support for the AVR-DA/DB with DxCore as the code would be quite similar. So to answer your question ... not yet, but coming soon!

**Comment by sstaub** [comment]
Thank's for the fast response, hope AVR-DA support will follow, I  ordered some of 28-pin DIP one direct from microchip, also 2 of your programmers from Tindie. Meanwhile I can use the code from SpenceKonde which should also work with the Nano, but with no HV.

**Comment by Dlloydev** [comment]
Added HV support for ATmega4809 Family
This includes the ATmega4809, ATmega4808, ATmega3209, ATmega3208, ATmega1609, ATmega1608, ATmega809 and ATmega808 devices. Pinout diagrams and new information added to the GitHub Wiki.

Also added HV support for the AVR DA, but getting compile errors due to missing pin definitions ... left an issue at the DxCore repository.

**Comment by Dlloydev** [comment]
New update with ATtiny and ATmega HV Programmer fixes, updated documentation with working 40-pin ATmega4809 on breadboard.

**Comment by Dlloydev** [comment]
I'll be watching for this upstream.

**Comment by Dlloydev** [comment]
Taking another look at this...
Should be able to add HV programming support for AVR-DA parts with 128K flash memory
(AVR128DA32, AVR128DA48 and AVR128DA64).

**Comment by Dlloydev** [comment]
Done!
Repo updated.
For pinout descriptions, just refer to the 28/48/64 pin images for the [DIY ATmega4809 HV UPDI Programmer](https://github.com/Dlloydev/jtag2updi/wiki/DIY-ATmega4809-HV-UPDI-Programmer).
